aimsumins/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("job/", include("job.urls", namespace="job")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Aimsumins Administration"
admin.site.site_title = "Aimsumins Admin Portal"
admin.site.index_title = "Welcome to Aimsumins Admin Portal"

job/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "job"

urlpatterns = [

]

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("services/", views.ServicesView.as_view(), name="services"),
    path("service/<slug>/", views.ServicesDetailView.as_view(), name="service-detail"),
    path("blogs/", views.BlogView.as_view(), name="blogs"),
    path("blog/<slug>/", views.BlogDetailView.as_view(), name="blog-detail"),
    path("gallery/", views.PortfolioView.as_view(), name="portfolio"),
    
    path("job/", views.JobListView.as_view(), name="job"),
    path("job/<slug>/", views.JobDetailView.as_view(), name="job-detail"),
    
    path('hire_enquiry/', views.HireEnquiryView.as_view(), name="hire-enquiry"),
]

job/models.py
from django.db import models
from django.urls import reverse_lazy
from datetime import datetime, timedelta, timezone

from tinymce.models import HTMLField
from versatileimagefield.fields import VersatileImageField
from datetime import datetime

# Create your models here.

JOB_TYPE = (
    ("Full Time", "Full Time"),
    ("Part Time", "Part Time"),
    ("Internship", "Internship"),
    ("Freelance", "Freelance"),
    ("Work From Home", "Work From Home"),
    ("Remote", "Remote"),
)

class Job(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    salary = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = HTMLField()
    job_expire = models.CharField(max_length=255)
    job_type= models.CharField(max_length=255, choices=JOB_TYPE,default="Full Time")
    job_role= models.CharField(max_length=255)
    education = models.CharField(max_length=255)
    experience = models.CharField(max_length=255)
    vacancies = models.IntegerField()
    location_embeded = models.TextField(help_text="Copy and paste embed code from google maps",null=True,blank=True)
    
    
    def get_absolute_url(self):
        return reverse_lazy('web:job-detail', kwargs={'slug': self.slug})
    
    
    
    def get_date(self):
        current_time = datetime.now().replace(tzinfo=None)
        job_date = self.date.replace(tzinfo=None)
        time_difference = current_time - job_date

        # Check if the job was posted today
        if time_difference.days == 0:
            return 'Today'
        
        # Calculate years, months, weeks, and days
        years = time_difference.days // 365
        months = time_difference.days // 30
        weeks = time_difference.days // 7
        days = time_difference.days

        if years > 0:
            return f"{years} {'year' if years == 1 else 'years'} ago"
        elif months > 0:
            return f"{months} {'month' if months == 1 else 'months'} ago"
        elif weeks > 0:
            return f"{weeks} {'week' if weeks == 1 else 'weeks'} ago"
        else:
            return f"{days} {'day' if days == 1 else 'days'} ago"

web/models.py
from django.db import models
from tinymce.models import HTMLField
from versatileimagefield.fields import VersatileImageField

from django.urls import reverse_lazy
# Create your models here.

class Service(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True, max_length=100)
    image=VersatileImageField(upload_to='services',help_text=" The recommended size is 850x450 pixels.")
    description=HTMLField()

    def get_absolute_url(self):
        return reverse_lazy('web:service-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title
    
    
    
    
class Blog(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True, max_length=200)
    date=models.DateField(blank=True, null=True)
    image=VersatileImageField(upload_to='blogs',help_text=" The recommended size is 650x450 pixels.")
    description=HTMLField()
    
    def get_absolute_url(self):
        return reverse_lazy('web:blog-detail', kwargs={'slug': self.slug})
    
    def __str__(self):
        return self.title
    
    
class Testmonial(models.Model):
    name=models.CharField(max_length=200)
    position=models.CharField(max_length=200,blank=True, null=True)
    description=models.TextField()
    
    def __str__(self):
        return self.name
    
    
class Faq(models.Model):
    question=models.CharField(max_length=200)
    answer=models.TextField()
    
    def __str__(self):
        return self.question
    
    
class PortfolioCategory(models.Model):
    name=models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Portfolio(models.Model):
    image=VersatileImageField(upload_to='portfolio',help_text=" The recommended size is 650x450 pixels.")
    
    class Meta:
        verbose_name = ("Gallery")
        verbose_name_plural = ("Gallery")
    
    
    def __str__(self):
        return str(self.image)
    
    
class Contact(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField()
    phone=models.CharField(max_length=200)
    subject=models.CharField(max_length=200)
    message=models.TextField()

    def str(self):
        return self.name
    
class Client_logo(models.Model):
    image=VersatileImageField(upload_to='client_logo')
    
    def __str__(self):
        return str(self.image)
    
class Team(models.Model):
    name=models.CharField(max_length=200)
    position=models.CharField(max_length=200)
    image=VersatileImageField(upload_to='team')
    
    def __str__(self):
        return self.name
    

class Counter(models.Model):
    number=models.CharField(max_length=200)
    title=models.CharField(max_length=200)
    plus_icon=models.BooleanField(default=True)
    
    def __str__(self):
        return self.title
    
    
class Main(models.Model):
    banner_title=models.CharField(max_length=200)
    banner_image=VersatileImageField(upload_to='main')
    banner_description=models.TextField()
    about_title=models.CharField(max_length=200)
    about_image=VersatileImageField(upload_to='main')
    about_description=models.TextField()
    
    def __str__(self):
        return self.banner_title
    
    class Meta:
        verbose_name = "Main"
        verbose_name_plural = "Main"
    

class HireEnquiry(models.Model):
    name=models.CharField(max_length=200)
    email=models.EmailField()
    phone=models.CharField(max_length=200)
    job=models.CharField(max_length=200)
   
    
    def __str__(self):
        return self.name

job/views.py
from django.shortcuts import render

# Create your views here.

templates/web/about.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}

<!-- Start Page Title Section -->
<div class="page-title-area">
	<div class="d-table">
		<div class="d-table-cell">
			<div class="container">
				<div class="page-title-content">
					<h2>About Us</h2>
					<ul>
						<li><a href="{% url "web:index" %}">Home</a></li>
						<li>About Us</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Page Title Section -->



<!-- Start About Section -->
<section class="about-area section-padding p-sm-30">
	<div class="container">
		<div class="row d-flex align-items-center">
			<div class="col-lg-6 col-md-12">
				<div class="about-content">
					<h6 class="sub-title">About Our Company</h6>
					<h2>{{main.about_title}}</h2>
					<p>{{main.about_description}}</p>
					
					{% comment %} <div class="about-btn-box">
						<a class="default-btn" href="about.html">Learn More <span></span></a>
					</div> {% endcomment %}
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
				<div class="about-image">
					<img src="{{main.about_image.url}}" alt="About image">
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End About Section -->

<section class="feature-section">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<div class="feature-single-item vision">
					<img src="{% static "web/img/icon/feature-icon-1.svg" %}" alt="icon">
					<h3>Vision</h3>
					<p class="text-justify">Our Vision is to become one of the leading and reputed human resources consulting firm operating globally especially middle east by maintaining our standards and creating value for all our Clients.</p>
					
				</div>
			</div>
			<div class="col-md-6">
				<div class="feature-single-item">
					<img src="{% static "web/img/icon/feature-icon-3.svg" %}" alt="icon">
					<h3>Mission</h3>
					<p class="text-justify">Our Mission is to develop long-term partnership with our Clients, and help them to transform day to day challenges into upcoming future successes. We are committed to meeting and achieving the expectations in providing extra ordinary service, awesome quality and outstanding value to our Clients.</p>
					
				</div>
			</div>
			
		</div>
	</div>
</section>

<!-- Start Team Section -->
<section class="team-area section-padding pt-50 p-sm-30">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-12">
				<div class="section-title">
					<h6 class="sub-title">Team Member</h6>
					<h2>Our Team</h2>
				</div>
			</div>
			{% for team in teams %}
			<div class="col-lg-3 col-md-6 ">
				<div class="single-team-box">
					<div class="team-image">
						<img src="{{team.image.url}}" alt="team">
						
					</div>
					<div class="team-info">
						<h3>{{team.name}}</h3>
						<span>{{team.position}}</span>
					</div>
				</div>
			</div>
			{% endfor %}
			
		</div>
	</div>
</section>
<!-- End Team Section -->


<!-- Start Counter Section -->
<section class="counter-area section-padding p-sm-30">
	<div class="container">
		<div class="row">
			{% for i in counters %}
			<div class="col-lg-3 col-md-6 col-6 counter-item">
				<div class="single-counter">
					<div class="counter-contents">
						<h2>
							<span class="counter-number">{{i.number}}</span>
							{% if i.plus_icon %}
							<span>+</span>
							{% endif %}
						</h2>
						<h3 class="counter-heading">{{i.title}}</h3>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<!-- End Counter Section -->

{% endblock %}

templates/web/blog-detail.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}

<!-- Start Page Title Section -->
<div class="page-title-area item-bg1">
	<div class="d-table">
		<div class="d-table-cell">
			<div class="container">
				<div class="page-title-content">
					<h2>Blog Details</h2>
					<ul>
						<li><a href="{% url "web:blogs" %}">Blog</a>
						</li>
						<li>Blog Details</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Page Title Section -->

<!-- Start Blog Details Section -->
<section class="blog-details-area ptb-100 section-50-padd">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-12 mx-auto">
				<div class="blog-details-desc">
					<div class="article-image">
						<img src="{{object.image.url}}" alt="image">
					</div>
					<div class="article-content">
						<div class="entry-meta">
							<ul>
								<li> <span>Posted On:</span> <a href="#">{{object.date}}</a></li>
								
							</ul>
						</div>
						<h3>{{object.title}}</h3>
						<p>{{object.description|safe}}</p>
						
					</div>
					
					
				</div>
			</div>
			
		</div>
	</div>
</section>
<!-- End Blog Details Section -->

{% endblock %}

templates/web/blog.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
	
	<!-- Start Page Title Section -->
	<div class="page-title-area item-bg1">
		<div class="d-table">
			<div class="d-table-cell">
				<div class="container">
					<div class="page-title-content">
						<h2>Blogs</h2>
						<ul>
							<li><a href="{% url "web:index" %}">Home</a>
							</li>
							<li>Blogs</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Title Section -->
	
	<!-- Start Blog Section -->
	<section class="blog-section section-padding section-50-padd">
		<div class="container">
			<div class="row">
				{% for item in blog_list %}
				<div class="col-lg-4 col-md-6">
					<div class="blog-single-item">
						<div class="blog-image">
							<a href="{{item.get_absolute_url}}">
								<img src="{{item.image.url}}" alt="image">
							</a>
						</div>
						<div class="blog-description">
							<ul class="blog-info">
								
								<li>
									<a href="#"><i class="bi bi-calendar-check"></i> {{item.date}}</a>
								</li>
							</ul>
							<div class="blog-text">
								<h3>
									<a href="{{item.get_absolute_url}}">
										{{item.title}}
									</a>
								</h3>
								<p>{{item.description|safe|truncatechars:100}}</p>
								<div class="blog-btn">
									<a href="{{item.get_absolute_url}}" class="read-more"><i class="bi bi-arrow-right-short"></i>
										Read More</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				
			</div>
		</div>
	</section>
	<!-- End Blog Section -->
	
{% endblock %}

templates/web/index.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
	<!-- Start Page Title Section -->
	<div class="page-title-area item-bg2">
		<div class="d-table">
			<div class="d-table-cell">
				<div class="container">
					<div class="page-title-content">
						<h2>Aim sumins</h2>
						<ul>
							<li><a href="/">Home</a>
							</li>
							<li>Aim sumins</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Title Section -->
<!-- Start Home Section -->
<div class="home-section home-2 p-sm-30">
	<div class="d-table">
		<div class="d-table-cell">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6 col-md-12">
						<div class="main-banner-content">
							<h1>{{main.banner_title}} 
								{% comment %} <span class="text-gradient">IT Support.</span> {% endcomment %}
							</h1>
							<p>{{main.banner_description}}</p>
							<div class="banner-btn">
								<a class="default-btn-one" href="{% url "web:services" %}">Our Service <span></span></a>
								
							</div>
						</div>
					</div>
					<div class="col-lg-6 col-md-12">
						<div class="banner-image">
							<img src="{{main.banner_image.url}}" alt="image">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	{% comment %} <div class="home-shape-animation">
		<div class="shape-1">
			<img src="{% static 'web/img/shape/1.png' %}" alt="shape image">
		</div>
		<div class="shape-2">
			<img src="{% static 'web/img/shape/2.png' %}" alt="shape image">
		</div>
		<div class="shape-3">
			<img src="{% static 'web/img/shape/3.png' %}" alt="shape image">
		</div>
		<div class="shape-4">
			<img src="{% static 'web/img/shape/4.png' %}" alt="shape image">
		</div>
		<div class="shape-5">
			<img src="{% static 'web/img/shape/5.png' %}" alt="shape image">
		</div>
		<div class="shape-6">
			<img src="{% static 'web/img/shape/6.png' %}" alt="shape image">
		</div>
		<div class="shape-7">
			<img src="{% static 'web/img/shape/7.png' %}" alt="shape image">
		</div>
	</div> {% endcomment %}
</div>
<!-- End Home Section -->

<!-- Start Services Two Section -->
<section class="testimonial-section section-padding p-sm-30 service-main pt-lg-0">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					
					<h2>Latest Jobs</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="service-slider owl-carousel owl-theme">
					{% for item in jobs %}
					<div class="job-card">
						<div class="single-services-item index-single-services">
						
						<h3>{{ item.title }}</h3>
						<p class="job-type">{{ item.job_type }}</p>
						<p>salary: {{ item.salary }}</p>

						<div class="services-btn">
							<a href="{{ item.get_absolute_url }}" class="read-more"> Details <i class="bi bi-arrow-right-short"></i></a>
						</div>
						
						</div>
					</div>
				{% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Services Two Section -->

<!-- Start Services Two Section -->
<section class="testimonial-section section-padding p-sm-30 service-main pt-lg-0">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h6 class="sub-title">What We Provide</h6>
					<h2>Our Services</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="service-slider owl-carousel owl-theme">
					{% for item in services %}
					<div class="single-services-two-item">
						<div class="">
							<div class="">
								<a href="{{item.get_absolute_url}}"><img src="{{item.image.url}}" alt="image"></a>
							</div>
							
						</div>
						<div class="services-two-content">
							<h3 class="mt-3">{{item.title}}</h3>
							<p>{{item.description|safe|truncatechars:100}}</p>
							<div class="services-btn">
								<a href="{{item.get_absolute_url}}" class="read-more"><i class="bi bi-arrow-right-short"></i> Read More</a>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Services Two Section -->

<!-- Start About Section -->
<section class="about-area bg-grey section-padding p-sm-30 index-about-padd">
	<div class="container">
		<div class="row d-flex align-items-center">
			<div class="col-lg-6 col-md-12">
				<div class="about-content">
					<h6 class="sub-title">About Our Company</h6>
					<h2>{{main.about_title}}</h2>
					<p>{{main.about_description}}</p>
					
					<div class="about-btn-box">
						<a class="default-btn" href="{% url "web:about" %}">Learn More <span></span></a>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
				<div class="about-image">
					<img src="{{main.about_image.url}}" alt="About image">
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End About Section -->



<!-- Start Counter Section -->
<section class="counter-area section-padding p-sm-30 ">
	<div class="container">
		<div class="row">
			{% for i in counters %}
			<div class="col-lg-3 col-md-6 col-6 counter-item">
				<div class="single-counter">
					<div class="counter-contents">
						<h2>
							<span class="counter-number">{{i.number}}</span>
							{% if i.plus_icon %}
							<span>+</span>
							{% endif %}
						</h2>
						<h3 class="counter-heading">{{i.title}}</h3>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</section>
<!-- End Counter Section -->






<!-- Start Faq Section -->
<section class="faq-section home-faq bg-grey section-padding p-sm-30">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-12">
				<div class="faq-img">
					<img src="{% static 'web/img/faq.png' %}" alt="images">
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
				<div class="section-title">
					<h6 class="sub-title">Faqs</h6>
					<h2>Short Faqs</h2>
				</div>
				<div class="faq-accordion first-faq-box">
					<ul class="accordion">

						{% for faq in faqs %}
						<li class="accordion-item">
							<a class="accordion-title" href="javascript:void(0)"> <i class="fa fa-plus"></i>{{ faq.question }}</a>
							<p class="accordion-content">{{ faq.answer }}</p>
						</li>
						{% endfor %}

					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Faq Section -->


<!-- Start About Section -->
<section class="about-area  section-padding pb-0 p-sm-30 ">
	<div class="container">
		<div class="row d-flex align-items-center">
			<div class="col-lg-6 col-md-12">
				<div class="about-image">
					<img src="{% static 'web/img/ceo2.jpg' %}" alt="About image">
				</div>
			</div>
			<div class="col-lg-6 col-md-12">
				<div class="about-content">
					<h2>Mini Suseel</h2>
					<h6 class="sub-title">CEO</h6>
					<p>With a visionary outlook that surpasses conventional HR practices, I, Mini Suseel, proudly serve as the CEO of AIM SUMINS HR CONSULTANCY LLC, leading a team of dedicated and adept consultants. Our journey commenced with my 15-year tenure as a successful entrepreneur in India, specifically Kerala, where I established and managed Sumins Homecare Products and Marketing. This rich experience laid the foundation for our consultancy's inception as a freelance service provider in the UAE market for 2 years, culminating in our evolution into an established entity in 2023.</p>

				</div>
			</div>
			
		</div>
	</div>
</section>
<!-- End About Section -->




<section class="blog-section section-padding p-sm-30">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h6 class="sub-title">Blog & Article</h6>
					<h2>Recent Blog</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="blog-slider owl-carousel owl-theme">
					{% for item in blogs %}
					<div class="blog-single-item">
						<div class="blog-image">
							<a href="{{item.get_absolute_url}}">
								<img src="{{item.image.url}}" alt="image">
							</a>
						</div>
						<div class="blog-description">
							<ul class="blog-info">
								
								<li>
									<a href="#"><i class="bi bi-calendar-check"></i> {{item.date}}</a>
								</li>
							</ul>
							<div class="blog-text">
								<h3>
									<a href="{{item.get_absolute_url}}">
										{{item.title}}
									</a>
								</h3>
								<p>{{item.description|safe|truncatechars:100}}</p>
								<div class="blog-btn">
									<a href="{{item.get_absolute_url}}" class="read-more"><i class="bi bi-arrow-right-short"></i>
										Read More</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>

<!-- Start Testimonial Section -->
<section class="testimonial-section section-padding pt-0 p-sm-30 testimonial-custom ">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h6 class="sub-title">Our Testimonial</h6>
					<h2>Client Feedback</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="testimonial-slider owl-carousel owl-theme">
					<!-- testimonials item -->
					{% for item in testmonials %}
					<div class="single-testimonial">
						
						<div class="testimonial-content">
							<p>{{ item.description }}</p>
						</div>
						
						<div class="testimonial-bio">
							<div class="bio-info">
								<h3>{{item.name}}</h3>
								<span>{{item.position}}</span>
							</div>
						</div>
					</div>
					{% endfor %}
					<!-- testimonials item -->
					
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Testimonial Section -->
{% if client_logos %}
<section class="testimonial-section section-padding p-sm-30 pt-0">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					<h6 class="sub-title">Trusted Clients</h6>
					<h2>Our Customers</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="clientlogo-slider owl-carousel owl-theme">
					{% for i in client_logos %}
					<div class="partner-item">
						<a href="#">
							<img src="{{i.image.url}}" alt="image">
						</a>
					</div>
					{% endfor %}
					

				</div>
			</div>
		</div>
	</div>
</section>
{% endif %}



{% if portfolios %}
<section class="testimonial-section section-padding p-sm-30 pt-0">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="section-title">
					
					<h2>Our Gallery</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12">
				<div class="service-slider owl-carousel owl-theme">
					{% for i in portfolios %}
					<div class="partner-item">
						<a href="#">
							<img src="{{i.image.url}}" alt="image">
						</a>
					</div>
					{% endfor %}
					

				</div>
			</div>
		</div>
	</div>
</section>
{% endif %}

{% endblock %}

templates/web/portfolio.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
	
	<!-- Start Page Title Section -->
	<div class="page-title-area">
		<div class="d-table">
			<div class="d-table-cell">
				<div class="container">
					<div class="page-title-content">
						<h2>Gallery</h2>
						<ul>
							<li><a href="{% url "web:index" %}">Home</a></li>
							<li>Gallery</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Title Section -->
	
	<!-- Start Portfolio Section -->
    <section class="portfolio-area section-padding section-50-padd">
        <div class="container">
            <div class="row">
				<div class="col-md-12">
					<div class="section-title">
						<h2>Our Gallery</h2>
					</div>
				</div>
               
            </div>
            <div class="portfolio-container">
				<div class="row">
                    <!-- portfolio-item -->
                    {% for item in object_list %}
                    <div class="col-lg-4 col-md-6 portfolio-grid-item all {{item.category.name|slugify}}">
                        <div class="portfolio-item">
							<img src="{{item.image.url}}" alt="image">
                           
                        </div>
                    </div>
                    {% endfor %}
                    <!-- portfolio-item -->
                    
                </div>
            </div>
        </div>
    </section>
    <!-- End Portfolio Section -->
	
{% endblock %}

templates/web/services.html
{% extends "web/base.html" %}
{% load static %}
{% block content %}
	
	<!-- Start Page Title Section -->
	<div class="page-title-area item-bg2">
		<div class="d-table">
			<div class="d-table-cell">
				<div class="container">
					<div class="page-title-content">
						<h2>Services</h2>
						<ul>
							<li><a href="{% url "web:index" %}">Home</a></li>
							<li>Services</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Page Title Section -->
	
	<!-- Start Services Section -->
	<section class="services-section section-padding section-50-padd">
		<div class="container">
			<div class="row">
				{% for item in service_list %}
				<div class="col-lg-4 col-md-6">
					<div class="single-services-two-item">
						<div class="">
							<div class="">
								<a href="{{item.get_absolute_url}}"><img src="{{item.image.url}}" alt="image"></a>
							</div>
							
						</div>
						<div class="services-two-content">
							<h3 class="mt-3">{{item.title}}</h3>
							<p>{{item.description|safe|truncatechars:100}}</p>
							<div class="services-btn">
								<a href="{{item.get_absolute_url}}" class="read-more"><i class="bi bi-arrow-right-short"></i> Read More</a>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>
		</div>
	</section>
	<!-- End Services Section -->
	

	
{% endblock %}