aimsumins/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("job/", include("job.urls", namespace="job")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Aimsumins Administration"
admin.site.site_title = "Aimsumins Admin Portal"
admin.site.index_title = "Welcome to Aimsumins Admin Portal"

job/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "job"

urlpatterns = [

]

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("services/", views.ServicesView.as_view(), name="services"),
    path("service/<slug>/", views.ServicesDetailView.as_view(), name="service-detail"),
    path("blogs/", views.BlogView.as_view(), name="blogs"),
    path("blog/<slug>/", views.BlogDetailView.as_view(), name="blog-detail"),
    path("gallery/", views.PortfolioView.as_view(), name="portfolio"),
    
    path("job/", views.JobListView.as_view(), name="job"),
    path("job/<slug>/", views.JobDetailView.as_view(), name="job-detail"),
    
    path('hire_enquiry/', views.HireEnquiryView.as_view(), name="hire-enquiry"),
]

templates/web/partials/footer.html
{% load static %}

<!-- Start Footer & Subscribe Section -->
<section class="footer-subscribe-wrapper">
    <!-- Start Footer Section -->
    <div class="footer-area ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <a class="footer-logo" href="#">
                            <img src="{% static 'web/img/logo.png' %}" class="white-logo" alt="logo">
                        </a>
                        <p>Empower Your Business with Aim sumins - Your Trusted Partner in Strategic HR Solutions and Organizational Excellence.</p>
                        <ul class="footer-social">
                            <li>
                                <a href="https://www.facebook.com/profile.php?id=61555417742074&mibextid=ZbWKwL"> <i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li>
                                <a href="https://t.me/+qgUCt9ND1iIwNTBk"> <i class="fab fa-telegram"></i></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/aimsumins"> <i class="fab fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/aimsumins/"> <i class="fab fa-instagram"></i></a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/aimsumins-hr-consultancy-2012842a9/"> <i class="fab fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <div class="footer-heading">
                            <h3>Our Services</h3>
                        </div>
                        <ul class="footer-quick-links">
                            {% for i in footer_services %}
                            <li><a href="{{ i.get_absolute_url }}">{{ i.title }}</a></li>
                            {% endfor %}
                           
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <div class="footer-heading">
                            <h3>Useful Links</h3>
                        </div>
                        <ul class="footer-quick-links">
                            <li><a href="{% url "web:about" %}">About Us</a></li>
                            <li><a href="{% url "web:services" %}">Services</a></li>
                            <li><a href="{% url "web:portfolio" %}">Gallery</a></li>
                            <li><a href="{% url "web:blogs" %}">Blogs</a></li>
                            <li><a href="{% url "web:contact" %}">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <div class="footer-heading">
                            <h3>Contact Info</h3>
                        </div>
                        <div class="footer-info-contact">
                            <i class="flaticon-phone-call"></i>
                            <h3>Phone</h3>
                            <span><a href="tel:+971509249880">+971 509249880</a></span><br>
                            <span><a href="tel:+971563238443">+971 563238443</a></span><br>
                            <span><a href="tel:+97145753827">+971 45753827</a></span>
                        </div>
                        <div class="footer-info-contact">
                            <i class="flaticon-envelope"></i>
                            <h3>Email</h3>
                            <span><a href="mailto:hr@aimsumins.com">hr@aimsumins.com</a></span><br>
                            <span><a href="mailto:admin@aimsumins.com">admin@aimsumins.com</a></span><br>
                            <span><a href="mailto:info@aimsumins.com">info@aimsumins.com</a></span>
                        </div>
                        <div class="footer-info-contact">
                            <i class="flaticon-placeholder"></i>
                            <h3>Address</h3>
                            <span>Office No.304, Fast Business Building, Nr.Al Twar Center, Al Qusais-2, Dubai, UAE</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Footer Section -->
</section>
<!-- End Footer & Subscribe Section -->

<!-- Start Copy Right Section -->
<div class="copyright-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <p><i class="far fa-copyright"></i> {% now "Y" %} Aim sumins - All Rights Reserved.</p>
            </div>
           
        </div>
    </div>
</div>
<!-- End Copy Right Section -->

templates/web/partials/header.html
{% load static %}

<!-- Start Navbar Section -->
<div class="navbar-area">
    <div class="techvio-responsive-nav {% if is_index %} index-navber-responsive {% endif %}">
        <div class="container">
            <div class="techvio-responsive-menu">
                <div class="logo">
                    <a href="{% url "web:index" %}">
                        <img src="{% static 'web/img/logo.png' %}" class="white-logo" alt="logo">
                        <img src="{% static 'web/img/logo.png' %}" class="black-logo" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="techvio-nav ">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light">
                <a class="navbar-brand" href="{% url "web:index" %}">
                    <img src="{% static 'web/img/logo.png' %}" class="white-logo" alt="logo">
                    <img src="{% static 'web/img/logo.png' %}" class="black-logo" alt="logo">
                </a>
                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url "web:index" %}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:about" %}" class="nav-link">About us</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:services" %}" class="nav-link">Services</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:job" %}" class="nav-link">Find a job</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:blogs" %}" class="nav-link">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:portfolio" %}" class="nav-link">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url "web:contact" %}" class="nav-link">Contact us</a>
                        </li>
                    </ul>
                    {% comment %} <div class="other-option">
                        <a class="default-btn" href="mailto:hr@aimsumins.com">Get It Support <span></span></a>
                    </div> {% endcomment %}
                    <div class="other-option">
                        <a class="default-btn" href="{% url "web:hire-enquiry" %}">Post a job <span></span></a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- End Navbar Section -->